### PR TITLE
fix missing symbol rados_set/unset_pool_full_try, M1 improvements

### LINKED ISSUE #13: ceph symbol not found
When I run `/usr/local/bin/ceph` I receive a `Symbol not found` error.

```
❯ /usr/local/bin/ceph -h
Traceback (most recent call last):
  File "/usr/local/Cellar/ceph-client/quincy-17.0.0-4483-g0def4cf21d8/libexec/bin/ceph", line 142, in <module>
    import rados
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/rados.cpython-39-darwin.so, 2): Symbol not found: _rados_set_pool_full_try
  Referenced from: /usr/local/lib/python3.9/site-packages/rados.cpython-39-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.9/site-packages/rados.cpython-39-darwin.so
```

### PR DESCRIPTION
**Pull request by thmour**
On the current revision the two API methods have a _ appended to them and they don't match the librados C api name, on ceph/master this is already fixed.
After fixing this, `ceph -h` had a missing python module "wcwidth".
Lastly, because on M1 homebrew installs libraries and include folders now to "/opt/homebrew/(include|lib)" by default for arm64, the executables will complain that they can't find the libraries needed on the given rpath which searches in "/usr/local/lib" and "/usr/lib". I tried using `MachO.open(file).add_rpath` and `MachO::Tools.add_rpath` with no success, looks like the syscall works.

fixes #13 #16

### CODE REVIEW

**Comment by 3ch01c** [comment]
I'm having a similar error on an Intel Mac.

```sh
$ ceph -h
Traceback (most recent call last):
  File "/usr/local/Cellar/ceph-client/quincy-17.0.0-4483-g0def4cf21d8/libexec/bin/ceph", line 142, in <module>
    import rados
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/rados.cpython-39-darwin.so, 2): Symbol not found: _rados_set_pool_full_try
  Referenced from: /usr/local/lib/python3.9/site-packages/rados.cpython-39-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.9/site-packages/rados.cpython-39-darwin.so
```

Do you know if your version works on Intel Macs? I'm trying to use it like:

```sh
brew tap thmour/homebrew-ceph-client
brew reinstall thmour/ceph-client/ceph-client
```

I don't know if I'm doing it right, but the problem persists.

**Comment by thmour** [comment]
@3ch01c hello, can you tell me the output of this?
```
nm -g /usr/local/lib/python3.9/site-packages/rados.cpython-39-darwin.so | grep full_try
```

File: ceph-client.rb [hunk 1]
```diff
@@ -32,6 +32,11 @@ class CephClient < Formula
     sha256 "b8eac752c5e14d3eca0e6dd9199cd627518cb5ec06add0de9d32baeee6fe645d"
   end
 
+  resource "wcwidth" do
+    url "https://files.pythonhosted.org/packages/89/38/459b727c381504f361832b9e5ace19966de1a235d73cdbdea91c771a1155/wcwidth-0.2.5.tar.gz"
+    sha256 "c4d647b99872929fdb7bdcaa4fbe7f01413ed3d98077df798530e5b04f116c83"
+  end
```
Comment (tchaikov) [inline ceph-client.rb:38]: hi @thmour , do you have the python backtrace caused by missing `wcwidth`? if yes, could you paste here? as i am not able to find the direct dependency on this python package by grep'ing it in the quincy tree:
```
$ git grep wcwidth
src/pybind/mgr/dashboard/frontend/package-lock.json:        "wcwidth": "^1.0.1"
src/pybind/mgr/dashboard/frontend/package-lock.json:    "wcwidth": {
src/pybind/mgr/dashboard/frontend/package-lock.json:      "resolved": "https://registry.npmjs.org/wcwidth/-/wcwidth-1.0.1.tgz",
```

Comment (thmour) [reply ceph-client.rb]:
```
thmour@Theofilos-MacBook-Pro homebrew-ceph-client % ceph -s
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ceph-client/quincy-17.0.0-4483-g0def4cf21d8/libexec/bin/ceph", line 153, in <module>
    from ceph_daemon import admin_socket, DaemonWatcher, Termsize
  File "/opt/homebrew/lib/python3.9/site-packages/ceph_daemon.py", line 24, in <module>
    from prettytable import PrettyTable, HEADER
  File "/opt/homebrew/Cellar/ceph-client/quincy-17.0.0-4483-g0def4cf21d8/libexec/vendor/lib/python3.9/site-packages/prettytable/__init__.py", line 1, in <module>
    from .prettytable import (
  File "/opt/homebrew/Cellar/ceph-client/quincy-17.0.0-4483-g0def4cf21d8/libexec/vendor/lib/python3.9/site-packages/prettytable/prettytable.py", line 45, in <module>
    import wcwidth
ModuleNotFoundError: No module named 'wcwidth'
```

Comment (tchaikov) [reply ceph-client.rb:38]: thanks!

**Review by tchaikov — APPROVED** [review]
